# Generated by Django 2.1.7 on 2020-06-03 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telecom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='references',
            name='biere',
        ),
        migrations.DeleteModel(
            name='Biere',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='References',
        ),
    ]
