# Generated by Django 2.1.7 on 2020-06-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecom', '0004_auto_20200607_0726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comptoir',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-name']},
        ),
        migrations.RemoveField(
            model_name='comptoir',
            name='reference',
        ),
        migrations.AddField(
            model_name='comptoir',
            name='description',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='comptoir',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='comptoir',
            name='ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='description',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='description',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='reference',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='description',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='comptoir',
            name='position',
            field=models.CharField(max_length=10),
        ),
    ]
