# Generated by Django 2.1.7 on 2020-06-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecom', '0005_auto_20200608_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptoir',
            name='reference',
            field=models.ManyToManyField(blank=True, related_name='reference', to='telecom.Reference'),
        ),
    ]
